---
title: "Data Science"
author: "Merlin Gérard, Estelle Strade, Hugo Phipps"
date: "11/8/2020"
output: 
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE, message=FALSE )

# Load your packages here
library(data.table)
library(ggplot2)
library(PerformanceAnalytics)
library(gridExtra)
library(gstat)
theme_set(theme_classic())
```

## Introduction

```{r}
#Retirer le '#' devant le fread correspondant à ton chemin en local

data3 <- fread("/Users/merlingerard/Desktop/projet_stat/Projet-STAT/groupe3.csv")
#data3 <- fread("C:/Users/hugop/Desktop/projet_stat/Projet-STAT/groupe3.csv")
#mets ton chemin ici Estelle

head(data3)
summary(data3)
```

### Graphes 

#### Cadmium

```{r}
#Cadmium
map_Cd <- ggplot(data3) + geom_point(aes(x=X, y=Y, color=Cd), size=1) + 
                 xlab("Longitude") + ylab("Lattitude") + 
                 ggtitle("Cadmium measures map") +
                 theme(plot.title=element_text(hjust=0.5)) + # center title
                 scale_color_gradient(name="Cadmium [mg/kg]", low='yellow', high='darkblue')
map_Cd
```

#### Plomb

```{r}
#Plomb
map_Pb <- ggplot(data3) + geom_point(aes(x=X, y=Y, color=Pb), size=1) + 
                 xlab("Longitude") + ylab("Lattitude") + 
                 ggtitle("Lead measures map") +
                 theme(plot.title=element_text(hjust=0.5)) + # center title
                 scale_color_gradient(name="Lead [mg/kg]", low='lightblue', high='darkblue')
map_Pb
```

#### Chrome

```{r}
#Chrome
map_Cr <- ggplot(data3) + geom_point(aes(x=X, y=Y, color=Cr), size=1) + 
                 xlab("Longitude") + ylab("Lattitude") + 
                 ggtitle("Chrome measures map") +
                 theme(plot.title=element_text(hjust=0.5)) + # center title
                 scale_color_gradient(name="Chrome [mg/kg]", low='yellow', high='darkgreen')
map_Cr
```

### Distribution des variables

```{r}
#Plomb
ggplot(data3, aes(x = Cd)) + # if you put 'aes' here, all geom_ functions will use rain as x
  geom_histogram(aes(y = ..density..,  # display density function (and not count)
                     fill = "Density histogram" ),
                 bins = 15, # number of bins
                 color = "white") + 
  geom_density(col = "lightsteelblue3", 
               aes(fill = "Fitted pdf"), 
               alpha = 0.2) +  
  xlab("Cd content [mg/kg]") + 
  ylab("f(x)") + 
  ggtitle("Density histogram of the Cadmium content") +
  stat_function(fun=dnorm, # display a normal distribution
                args=list(mean = mean(data3$Cd), sd = sd(data3$Cd)), # with mean and sd of rain
                aes(color="Normal pdf"),
                size= 1) + # width of the line
  scale_fill_manual("", values = c("Density histogram"="lightsteelblue2",
                                    "Fitted pdf"=alpha("lightsteelblue3",.2))) +
  scale_color_manual("", values="red")

ggplot(data3, aes(x = Cd)) + 
  stat_ecdf(geom = "step", aes(color = "Estimated cdf")) +  # Estimated Cumulative Density Function
  xlab("Cd content [mg/kg]") + 
  ylab("F(x)") + 
  ggtitle("Estimated vs normal cdf of the rain") +
  stat_function(fun = pnorm, # display a normal cumulative distribution
                args = list(mean = mean(data3$Cd), sd = sd(data3$Cd)), 
                aes(color = 'Normal cdf'),
                size= 1) +
  scale_color_manual("", values = c("Estimated cdf" = "black",
                                    "Normal cdf" = "red")) 
```

### Corrélations

```{r}
#scatterplots
h1 <- ggplot(data3) + geom_histogram(aes(x=Cd), bins=10, color='white')
h2 <- ggplot(data3) + geom_histogram(aes(x=Pb), bins=10, color='white')
h3 <- ggplot(data3) + geom_histogram(aes(x=Cr), bins=10, color='white')
p1 <- ggplot(data3) + geom_point(aes(x=Cd, y=Pb))
p2 <- ggplot(data3) + geom_point(aes(x=Cd, y=Cr))
p3 <- ggplot(data3) + geom_point(aes(x=Pb, y=Cr))
gNA <- ggplot(data3) + theme_void() # This is just an empty plot.

grid.arrange(h1,p1,p2,gNA, h2,p3,gNA,gNA,h3,
             ncol=3, top="Scatterplots")

#Correlation chart
chart.Correlation(data3[,.(Cd,Pb,Cr)])
```


